### ISSUE TITLE
Admin is always redirected to upgradesettings.php after installation

### ISSUE THREAD

**Issue by melanietreitinger** [eledia/block_eledia_adminexamdates#2]
After the installation the admin is always redirected to `upgradesettings.php`.
Clicking the `Save changes` button has no effect.

![Screenshot 2023-03-14 at 10-40-42 Online-Exam-Test Plugins Administration New settings](https://user-images.githubusercontent.com/66598405/225004157-c5feb149-9d7c-4bbe-aedc-c054c4869749.png)

**Comment by eledia** [comment]
Thanks for notice that problem, - we will fix that soon. 
As a workaround you need all the steps in the installation guide for activation of the rest webservice first an then you can go to the settingspage of the plugin https://yoururl.com/admin/settings.php?section=blocksettingeledia_adminexamdates and there you can load the exam course categories by clicking the checkbox in the field "reloaddepartments" and then save-button in the second step.

**Comment by melanietreitinger** [comment]
Thanks for the answer. I followed all the steps in the installation guide and checked the checkbox for "reloaddepartments".
I am not sure what is supposed to happen next - the department list is empty when I click on "New exam date" in the block.

**Comment by eledia** [comment]
In the plugin settings https://yoururl.com/admin/settings.php?section=blocksettingeledia_adminexamdates you need first to choose the departments in the list of the field "departments" with Ctrl-click or Shift-click and then click the save-button. If you dont see the list of departments in this settings field, then you need to create the course categories first in the right place, and load it again in the plugin settings.

**Comment by melanietreitinger** [comment]
OK, I was missing a proxy setting for the webservice - now it es there! 🙈

But `/admin/index.php` still redirects to `/admin/upgradesettings.php`.

![grafik](https://user-images.githubusercontent.com/66598405/225644810-2c709a03-f73e-469a-a89f-04ff54d20bcf.png)

**Comment by melanietreitinger** [comment]
When I try to book a room, there are still no departments:

![grafik](https://user-images.githubusercontent.com/66598405/225645489-fb185394-f24b-4322-a74a-f12a330a9920.png)

**Comment by melanietreitinger** [comment]
Well, it seems you need more than one department category, then they show up... 🙃

**Comment by eledia** [comment]
1.) In the examination system you need one course category for the "exam environment" with this course category ID: 'EXAMENV'. 

2.) All the subcategories of this category will be load in the plugin settings select field "department" - if there is no visible department in this field, maybe your webservice is not working correctly. You can switch on "Developer Mode" to see an error.

**Comment by melanietreitinger** [comment]
OK, apparently it took some time to load the categories, now they are there. 
Thanks.

I also found out that I have to create a cohort with teachers to book an exam date.

The redirect to `/admin/upgradesettings.php` is gone now!
