### ISSUE TITLE
The {$ a-> index} single exam date of the exam: ' {$ a-> name} ' has been saved.

### ISSUE THREAD

**Issue by melanietreitinger** [eledia/block_eledia_adminexamdates#4]
This is the message after clicking on "submit" for an exam room:

![grafik](https://user-images.githubusercontent.com/66598405/225711286-c62560a8-6a90-4f59-9995-84e9432ea486.png)

![grafik](https://user-images.githubusercontent.com/66598405/225711391-9147e4ab-0f5f-49f8-a60d-beaca8542cd5.png)

**Comment by eledia** [comment]
Thanks for reporting, we fixed this wrong string.
